Ref
Abhijithchintu/phoenix pull request #55
Opened 2023-05-03 11:50 UTC by Abhijithchintu

2023-05-03 15:59 UTC, manu156 approved these changes, later dismissed

2023-05-04 15:47 UTC, manu156 requested changes

2023-05-04 15:47 UTC, manu156 commented on Chat/.env
> +MONGO_URI="mongodb+srv://abhichintu7:Mongo%401234@cluster0.g0z1y7n.mongodb.net/?retryWrites=true&w=majority"
can we deploy this on local?

2023-05-04 15:47 UTC, manu156 commented on Chat/db/mongodb/schema.js
> +    user_name: String,
what is the use of user_name?

2023-05-04 15:47 UTC, manu156 commented on Chat/db/mongodb/schema.js
> +    receiver_name: String,
can we use receiver_client_id instead of name?

2023-08-09 19:52 UTC, AnuguRakeshReddy submitted a review, later dismissed
Do better coding, idiot!

2023-08-19 18:16 UTC, manu156 submitted a review, later dismissed

2023-09-10 06:38 UTC, manu156 approved these changes

2023-09-10 06:39 UTC, manu156 commented
resolved merge conflicts @Abhijithchintu . merging.

2023-09-10 06:39 UTC, merged